INSERT INTO ticket (usuario, estatus, fecha_creacion, fecha_actualizacion)
VALUES 
    ('usuario1', 'ABIERTO', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
    ('usuario2', 'CERRADO', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
    ('usuario3', 'ABIERTO', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
    ('usuario4', 'ABIERTO', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
    ('usuario5', 'CERRADO', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
    ('usuario6', 'ABIERTO', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
    ('usuario7', 'ABIERTO', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
    ('usuario8', 'CERRADO', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
    ('usuario9', 'ABIERTO', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
    ('usuario10', 'ABIERTO', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
    ('usuario11', 'CERRADO', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
    ('usuario12', 'ABIERTO', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());